In [2]:
#Import Dependencies
from matplotlib import pyplot as plt
from scipy.stats import linregress
import numpy as np
from sklearn import datasets
import pandas as pd
from pathlib import Path

In [10]:
# The path to our CSV file
county_data = Path("countycancer.csv")

# Read our cancer data into pandas
county_df = pd.read_csv(county_data)
county_df

,County,FIPS,"Age-Adjusted Incidence Rate([rate note]) - cases per 100,000",Lower 95% Confidence Interval,Upper 95% Confidence Interval,CI*Rank([rank note]),Lower CI (CI*Rank),Upper CI (CI*Rank),Average Annual Count,Recent Trend,Recent 5-Year Trend ([trend note]) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,US (SEER+NPCR)(1),0.0,442.3,442,442.6,N/A,N/A,N/A,1698328,stable,-0.3,-0.6,0.1
1,"Union County, Florida(6)",12125.0,1237.4,1165.6,1312.8,N/A,1,1,237,stable,0.6,-0.5,1.9
2,"Palo Alto County, Iowa(7)",19147.0,658.1,591.1,731.1,N/A,1,6,82,rising,4.8,0.2,15.4
3,"Treasure County, Montana(6)",30103.0,652.2,401,1007.4,N/A,1,55,7,stable,-1.1,-5.6,3.3
4,"Polk County, Texas(7)",48373.0,633.6,604.6,663.7,N/A,1,4,425,rising,2.2,1.2,4.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3171,7 Source: SEER November 2022 submission.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3172,8 Source: Incidence data provided by the SEER ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3173,Data not available [http://statecancerprofiles...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3174,Data for the United States does not include da...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3175,Data for the United States does not include Pu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
county_data[['County','']] = df['V'].str.split(',',expand=True)

In [9]:
#Population Data
# The path to our CSV file
county_pop = Path("Ruralurbancontinuumcodes2023.csv")

# Read our cancer data into pandas
county_pop_df = pd.read_csv(county_pop)
county_pop_df.tail

,FIPS,State,County_Name,Population_2020,RUCC_2023,Description
0,1001,AL,Autauga County,"58,805",2.0,"Metro - Counties in metro areas of 250,000 to ..."
1,1003,AL,Baldwin County,"231,767",3.0,Metro - Counties in metro areas of fewer than ...
2,1005,AL,Barbour County,"25,223",6.0,"Nonmetro - Urban population of 5,000 to 20,000..."
3,1007,AL,Bibb County,"22,293",1.0,Metro - Counties in metro areas of 1 million p...
4,1009,AL,Blount County,"59,134",1.0,Metro - Counties in metro areas of 1 million p...
...,...,...,...,...,...,...
3230,72151,PR,Yabucoa Municipio,"30,426",1.0,Metro - Counties in metro areas of 1 million p...
3231,72153,PR,Yauco Municipio,"34,172",2.0,"Metro - Counties in metro areas of 250,000 to ..."
3232,78010,VI,St. Croix Island,"41,004",5.0,"Nonmetro - Urban population of 20,000 or more,..."
3233,78020,VI,St. John Island,"3,881",9.0,"Nonmetro - Urban population of fewer than 5,00..."
3234,78030,VI,St. Thomas Island,"42,261",5.0,"Nonmetro - Urban population of 20,000 or more,..."

In [13]:
county_pop_df['Population_2020'] = county_pop_df['Population_2020'].str.replace(',', '').astype(int)

AttributeError: Can only use .str accessor with string values!

In [16]:
#groupby and summattion

state_populations = county_pop_df.groupby('State')['Population_2020'].sum()

print(state_populations)

State
AK      733391
AL     5024279
AR     3011524
AS       49710
AZ     7151502
CA    39538223
CO     5773714
CT     3605944
DC      689545
DE      989948
FL    21538187
GA    10711908
GU      153836
HI     1455271
IA     3190369
ID     1839106
IL    12812508
IN     6785528
KS     2937880
KY     4505836
LA     4657757
MA     7029917
MD     6177224
ME     1362359
MI    10077331
MN     5706494
MO     6154913
MP       47329
MS     2961279
MT     1084225
NC    10439388
ND      779094
NE     1961504
NH     1377529
NJ     9288994
NM     2117522
NV     3104614
NY    20201249
OH    11799448
OK     3959353
OR     4237256
PA    13002700
PR     3285874
RI     1097379
SC     5118425
SD      886667
TN     6910840
TX    29145505
UT     3271616
VA     8631393
VI       87146
VT      643077
WA     7705281
WI     5893718
WV     1793716
WY      576851
Name: Population_2020, dtype: int32